# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.memory = 4096
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Envirosensor
  config.vm.define "envirosensor" do |envirosensor|
    envirosensor.vm.hostname = "envirosensor.test"
    envirosensor.vm.network :private_network, ip: "192.168.56.90"
    
    envirosensor.vm.provider :virtualbox do |v|
        v.memory = 512
        v.cpus = 1
      end

    envirosensor.vm.provision :ansible do |ansible|
      ansible.playbook = "provisioning/envirosensor/main.yml"
      ansible.inventory_path = "provisioning/envirosensor/inventory.ini"
      ansible.become = true
    end
  end

  # Mongo
  config.vm.define "db" do |db|
    db.vm.hostname = "db.test"
    db.vm.network :private_network, ip: "192.168.56.91"

    db.vm.provision :ansible do |ansible|
      ansible.playbook = "provisioning/mongo/main.yml"
      ansible.inventory_path = "provisioning/mongo/inventory"
      ansible.become = true
    end
  end

end